#!/usr/bin/env python3

import gi
import signal

gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
gi.require_version('Notify', '0.7')

from datetime import datetime
from gi.repository import Gtk
from gi.repository import AppIndicator3
from gi.repository import Notify


APP_ID = 'indicator-github-status'
APP_NAME = 'Github Status Indicator'
APP_ICON = 'indicator-github-status'
APP_VERSION = '0.1.0'


class Indicator(object):
    def __init__(self):
        builder = Gtk.Builder()
        builder.add_from_file('gui.glade')

        self.indicator = AppIndicator3.Indicator.new(
            APP_ID,
            APP_ICON,
            AppIndicator3.IndicatorCategory.SYSTEM_SERVICES)
        self.indicator.set_status(AppIndicator3.IndicatorStatus.ACTIVE)

        self.menu = builder.get_object('menu')
        self.menu.show()
        self.indicator.set_menu(self.menu)

        self.status = builder.get_object('menuitem_status')

        self.preferences = builder.get_object('preferencesdialog')

        self.about = builder.get_object('aboutdialog')
        self.about.set_version(APP_VERSION)

        builder.connect_signals(self)

    def get_status(self):
        self.status.set_label(str(datetime.now()))

    def on_refresh(self, menuitem, data=None):
        self.get_status()

    def on_preferences(self, menuitem, data=None):
        self.preferences.set_position(Gtk.WindowPosition.CENTER_ALWAYS)
        self.preferences.run()
        self.preferences.hide()

    def on_about(self, menuitem, data=None):
        self.about.set_position(Gtk.WindowPosition.CENTER_ALWAYS)
        self.about.run()
        self.about.hide()

    def on_quit(self, menuitem, data=None):
        Notify.uninit()
        Gtk.main_quit()


indicator = Indicator()
indicator.get_status()
Notify.init(APP_ID)
signal.signal(signal.SIGINT, signal.SIG_DFL)
Gtk.main()
