#!/usr/bin/env python3

import signal

from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator
from gi.repository import Notify as notify


INDICATOR_ID = 'indicator-github-status'


def main():
    indicator = appindicator.Indicator.new(
    	INDICATOR_ID,
    	gtk.STOCK_INFO,
    	appindicator.IndicatorCategory.SYSTEM_SERVICES)
    indicator.set_status(appindicator.IndicatorStatus.ACTIVE)
    indicator.set_menu(build_menu())
    notify.init(INDICATOR_ID)
    gtk.main()


def build_menu():
    menu = gtk.Menu()
    item_quit = gtk.MenuItem('Quit')
    item_quit.connect('activate', quit)
    menu.append(item_quit)
    menu.show_all()
    return menu
 

def quit(_):
    notify.uninit()
    gtk.main_quit()


if __name__ == "__main__":
	signal.signal(signal.SIGINT, signal.SIG_DFL)
	main()
